# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cidade-alta-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cidadealta.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e2f0d75bc17943579a561a68587f610d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e13ba0dff7e24c0fa835595dfa83c68f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cidadealta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2f0d75bc17943579a561a68587f610d }}/cidade-alta-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cidade-alta-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9f3057df3ff43cc88c9ca37988bcf92 }}
        images: 'cidadealta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2f0d75bc17943579a561a68587f610d }}/cidade-alta-api:${{ github.sha }}'